### PR TITLE
Issue/54 git workflow

### PR DESCRIPTION
**Pull request by mairead**
[Adopt new worfklow](https://github.com/epimorphics/hmlr-linked-data/issues/54)

- updated makefile
- updated dockerfile
- updated entrypoint
- updated env config to remove vars from dockerfile
- add items to gitignore and dockerignore

### CODE REVIEW

**Review by andrew-pickin-epi — APPROVED** [review]
Some minor changes requested but nothing that should require another review.

**Comment by ijdickinson** [comment]
I built the image locally with `make image`, which seems to have worked OK. But it won't run:

```sh
[~/projects/hmlr/lr-landing]  (issue/54-git-workflow)
ian@alder $ docker image ls
REPOSITORY                                                                TAG                IMAGE ID       CREATED             SIZE
173681544495.dkr.ecr.eu-west-1.amazonaws.com/epimorphics/lr-landing/dev   1.5.6-2a2fe4a      278bf2d2756d   About an hour ago   555MB
<none>                                                                    <none>             b221bbcc3c3e   About an hour ago   573MB
ruby                                                                      2.6.6-alpine3.10   ca7ab3efe843   20 months ago       48.8MB
[~/projects/hmlr/lr-landing]  (issue/54-git-workflow)
ian@alder $ make run
Error response from daemon: No such container: lr_landing
make: [Makefile:69: run] Error 1 (ignored)
Error: No such container: lr_landing
make: [Makefile:70: run] Error 1 (ignored)
sh: can't open '/app/entrypoint.sh': Not a directory
make: *** [Makefile:71: run] Error 2
[~/projects/hmlr/lr-landing]  (issue/54-git-workflow)
```

Just running the image directly with docker has the same problem with the entrypoint:

```sh
[~/projects/hmlr/lr-landing]  (issue/54-git-workflow)
ian@alder $ docker run 278bf2d2756d
sh: can't open '/app/entrypoint.sh': Not a directory
```

**Comment by ijdickinson** [comment]
Update on this: if I change line 46 of the `Dockerfile` to:

```docker
COPY entrypoint.sh /app/entrypoint.sh
```

the image will run. But then it hits another error:

```sh
[~/projects/hmlr/lr-landing]  (issue/54-git-workflow)
ian@alder $ make run
Error response from daemon: No such container: lr_landing
make: [Makefile:69: run] Error 1 (ignored)
Error: No such container: lr_landing
make: [Makefile:70: run] Error 1 (ignored)
mkdir: can't create directory './tmp': Permission denied
make: *** [Makefile:71: run] Error 1
```

**Comment by ijdickinson** [comment]
I had to make two more changes to get the `make run` to work for me:

- line 42 in `Dockerfile`:
  `COPY --from=builder --chown=app /usr/src/app .`

- line 20 in `entrypoint.sh`: remove spaces around `:-`

**Review by ijdickinson — APPROVED** [review]
With the minor changes I added in earlier comments, this is working locally (with a simple proxy so that it mimics the `/app/root` deployment). Ltgm :+1:

**Pull request merged**
