### PR TITLE
Feature/ansible deployment

### PR DESCRIPTION
**Pull request by mika018**
@bogdanadrianmarc Please also try building a running the image locally as part of the review.
@andrew-pickin-epi Just have a look through to see if there is anything obvious missing.

### CODE REVIEW

**Comment by mika018** [comment]
@bogdanadrianmarc Do you mind having a look at the failing tests please? Once that's sorted out and you're happy with the changes I'll merge the PR.

**Comment by bogdanadrianmarc** [comment]
After some investigation on the failing tests, they seem to have sprung up from the updated `Gemfile.lock`. I've reverted the update in this PR: https://github.com/epimorphics/lr-landing/pull/59

If of any future use, the changes I made for dockerizing should be in this 3 PRs:
- https://github.com/epimorphics/lr-landing/pull/48
- https://github.com/epimorphics/lr-landing/pull/50
- https://github.com/epimorphics/lr-landing/pull/52

**Comment by ijdickinson** [comment]
I don't think it's OK to just say that the tests failed because the `Gemfile.lock` changed. We should properly diagnose the causes of the failures. Looking at the `Gemfile.lock` changes that you reverted, I note that, for example, it rolls back the version of the JSON rails logger and LR common styles dependencies. Does this mean that we're not running the latest versions of these key dependencies now? That seems like a bad thing

**Comment by bogdanadrianmarc** [comment]
Tests are failing because of `lr_common_styles`, previously we had version `1.7.2` that had working tests, the updated `Gemfile.lock` with failing tests has version `1.8.5`. Latest tagged and released version is `1.7.2`, so I'm unable to try versions incrementally and check where exactly breaks.

From the failing tests we have:
Screenshot 2021-09-16 at 14 13 54

This seems to be related to the cookie and footer changes on `lr_common_styles`:
Screenshot 2021-09-16 at 14 11 19

@joescottdave I know you've done some changes on that, do you know why these fail?

**Comment by joescottdave** [comment]
Going to merge these changes now that the tests pass.

**Pull request merged**
