### PR TITLE
HMLR Accessibility Statement Updates

### PR DESCRIPTION
**Pull request by jonrandahl**
This PR resolves ticket [#106](https://github.com/epimorphics/hmlr-linked-data/issues/106) and holds the latest updates for the Accessibility Statements (English and Welsh)

### CODE REVIEW

**Review by joescottdave — COMMENTED** [review]
Is a linter responsible for changing all of the apostrophes?

**Comment by jonrandahl** [comment]
> Is a linter responsible for changing all of the apostrophes?

Yes, however I'm now wondering if it was absolutely necessary, with possible alternatives being using `&#8217;` for "’" and `&#8211;` for replacing "–"

@joescottdave do you know something I don't? 😜

**Comment by joescottdave** [comment]
I suppose it's ultimately harmless and fairly standard practice at this point to use single quotations in place of apostrophes, just an odd thing for a linter to decide to enforce

**Review by joescottdave — APPROVED** [review]
LGTM

**Pull request merged**
